name: utils
version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.0.14
  retry: ^3.1.2
  flutter_multi_formatter: ^2.13.10
  get: ^4.6.6
  either_dart: ^1.0.0
  image_fade: ^0.6.2
  freezed_annotation: any
  async: ^2.11.0
  sliver_tools: ^0.2.12
  json_annotation: any
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: any
  json_serializable: any
